default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: admin123

development:
  <<: *default
  database: karipic

test:
  <<: *default
  database: karipic_test

production:
  <<: *default
  database: karipic_production
  username: karipic
  password: <%= ENV["KARIPIC_DATABASE_PASSWORD"] %>
